# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('storage_size', models.IntegerField()),
                ('number_uploads', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('so', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.TextField()),
                ('isp', models.TextField()),
                ('traceroute', models.TextField()),
                ('owner_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=3)),
                ('status', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Host')),
            ],
        ),
    ]
