# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='number_uploads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='storage_size',
            field=models.IntegerField(null=True),
        ),
    ]
