# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20170105_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filexml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='documents/')),
                ('file_path', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Collection')),
            ],
        ),
    ]
