# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_filexml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filexml',
            old_name='file_name',
            new_name='file_xml',
        ),
        migrations.RemoveField(
            model_name='filexml',
            name='file_path',
        ),
    ]
