# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_auto_20170106_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='banner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='isp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='organization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='so',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='traceroute',
            field=models.TextField(null=True),
        ),
    ]
