# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_auto_20170108_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='file_id',
            field=models.IntegerField(null=True),
        ),
    ]
