# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_port_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='file_id',
        ),
        migrations.AddField(
            model_name='host',
            name='file_id',
            field=models.IntegerField(null=True),
        ),
    ]
