# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_auto_20170109_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostname',
            field=models.TextField(null=True),
        ),
    ]
